# Generated by Django 4.0.1 on 2022-01-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate_reference',
            new_name='candidate_ref',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='candidate_reference',
            new_name='candidate_ref',
        ),
    ]
